### ISSUE TITLE
Error in samples/MapMemoryBench/MapMemoryBench.cpp

### ISSUE THREAD

**Issue by nicolacdnll** [preshing/junction#15]
Line 47 of *samples/MapMemoryBench/MapMemoryBench.cpp* reads like follows
`map->insert(key, (void*) uptr(key));`

but, I guess, it should be:
`map->assign(key, (void*) uptr(key));`

The error when executing `python python TestAllMaps.py .` says:
```
MapMemoryBench.cpp:47:22:
error: junction::extra::MapAdapter::Map’ has no member named ‘insert’
                 map->insert(key, (void*) uptr(key));
```

**Comment by preshing** [comment]
Indeed it should be. Thanks.
