### ISSUE TITLE
Problem with same hash values

### ISSUE THREAD

**Issue by rigazilla** [preshing/junction#16]
I've a problem with keys with the same hash value.
It seems that they are overwritten. I've cut down the problem in a sample here:

https://github.com/rigazilla/junction-sample/tree/example-constant-hash

**Comment by preshing** [comment]
Hi rigazilla,

Junction maps currently only support integer and pointer-sized keys with an invertible hash, so every key should have a unique hash. For more complex keys, I've had ways of supporting them in mind but I personally haven't had any need for them yet.

Sorry this wasn't more obvious. Indeed the only mention I found for this rule was in the blog post [A Resizable Concurrent Map](http://preshing.com/20160222/a-resizable-concurrent-map/). I'll add a note in the README.
