### ISSUE TITLE
Consider prividing insert_or_assign method as in C++17 std lib.

### ISSUE THREAD

**Issue by ilyapopov** [preshing/junction#2]
In C++17, there will be an [`insert_or_assign`](http://en.cppreference.com/w/cpp/container/unordered_map/insert_or_assign) method in associative containers. Consider renaming `set` to `inset_or_assign` or providing an alias for consistency with std library.

**Comment by preshing** [comment]
That's good to know. Thanks ilyapopov.

**Comment by preshing** [comment]
I renamed `set` to `assign`, which is a bit closer to C++17 terminology. `assign` returns the key's previous value, so if you want to know whether it inserted a new item, check for `NullValue`.
