### ISSUE TITLE
issue when inserting into concurrent map

### ISSUE THREAD

**Issue by mdevico** [preshing/junction#22]
Hi,

I have a seemingly simple test program which hangs on my machine under certain circumstances:

```
#include <junction/ConcurrentMap_Leapfrog.h>
#include <iostream>

struct Value
{
    int v;
};

using ConcurrentMap = junction::ConcurrentMap_Leapfrog<int,Value*>;

int main()
{
    ConcurrentMap cmap(10000);
    Value value{ 0 };

    //for (int i = 0; i < 1000000; ++i) // locks in 158th assign
    for (int i = 999999; i >= 0; --i) // works as expected
    {
        cmap.assign(i, &value);
        std::cout << "inserted " << i << "\n";
    }

    std::cout << "done\n";
}
```
As you can see from the comment around the for loops, one case works as expected (completes without error) while the other one hangs.  I am at a loss to explain why.  Is this a bug, or a known issue?  Or am I doing something stupid?

Thanks for your time.

**Comment by mdevico** [comment]
Update: yes I know I was missing a zero in the call to the constructor.  When I change that to 1000000, it gets a little bit further along, but still hangs.  If I don't supply a size to the constructor, then both loops work fine.

**Comment by preshing** [comment]
Hi mdevico,

The initial table size (passed to the constructor) must be a power of 2. You should see the assert if you run in Debug mode.

    TURF_ASSERT(turf::util::isPowerOf2(tableSize));
