### ISSUE TITLE
supporting  C++11 rules   issue 

### ISSUE THREAD

**Issue by lion117** [preshing/junction#3]
hi , when i try to run the [example]
(https://github.com/preshing/junction/blob/master/samples/MallocTest/MallocTest.cpp) in junction , 
IDE throw error which in the junction libs
![q -20160229152448](https://cloud.githubusercontent.com/assets/3996029/13388312/d1cb47b0-def9-11e5-86bd-6d208dc98fb7.png)
![q -20160229152414](https://cloud.githubusercontent.com/assets/3996029/13388317/e0307e9c-def9-11e5-9c4f-409df3fa9546.png)

system: win7 64bit
IDE: VS 2013

i did some digs , noted that the reason cause error  is the IDE is not  completely  compatibility with C++ 11. 
VS2013  IDE  doesn't support the following usage  

```C++
class UnitTest    // in VS2013
{
	const static int a = 10;    // VALID 
	const static string c = "good moringint";  // invalid 
	const static float d = 1.254;  // invalid 
	const static char e = '4';  // invalid 
};
```
> **Upgrading  IDE VS2013 to VS2015**  is not my option which is not free. 
Modifying  source  code to fix the issue in VS2013 is my only way to apply junction .

**Comment by preshing** [comment]
OK, I didn't realize that was a C++11-specific usage. Pull requests are welcome.

By the way, VS2015 Community Edition is free.
