### ISSUE TITLE
Junction as headers only 

### ISSUE THREAD

**Issue by WilliamTambellini** [preshing/junction#38]
Hi
Just seen this comment on 
https://preshing.com/20160201/new-concurrent-hash-maps-for-cpp
:
"People would obviously prefer a header-only, C++11 style implementation of Junction that they can just drop into any project. The thing is, the code is pretty experimental, so I wouldn't feel comfortable if a lot of people did that anyway."

Could indeed be Junction converted to some headers only lib ?
 
Congrats for the nice lib anyway,
Kind

**Comment by preshing** [comment]
Someone could do this, but I don't plan to.
