### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by quader-enterprises** [preshing/junction#39]
1. "Hash function must be invertible, so that every key has a unique hash". This seems like a severe limitation. std::map deals with collisions without issues. Why not use a thread-safe queue to remove the limitation ?

2. How about TTL, LRU and LFU ?

**Comment by preshing** [comment]
> This seems like a severe limitation

I agree.

> Why not use a thread-safe queue to remove the limitation ?

I'm not sure I see how that changes anything.

> How about TTL, LRU and LFU ?

I'm not too sure what you're talking about.

**Comment by quader-enterprises** [comment]
Lock-free queue to deal with hash key contentions. 

TTL = Time-to-live, LRU=Least Recently Used, LFU=Least Frequently Used

Caches like Redis have all this except Redis is out-of-process. Don't know how Junction performs relative to Redis.

**Comment by preshing** [comment]
OK, I guess you are comparing the Junction maps to Redis. I have no Redis experience, but Redis is clearly a mature product, whereas I still consider Junction pretty experimental. I haven't had the resources (ie. time) to evolve Junction into a more robust, off-the-shelf kind of library. But thanks for the info.
