### ISSUE TITLE
insertOrFind unexpected behavior

### ISSUE THREAD

**Issue by MonkeyBreaker** [preshing/junction#49]
Hi, 

First of all, thank you for the great library and blog, they are great material !
I'm currently using `ConcurrentMap_Leapfrog` and got excellent performances and results.
But, when I integrated with one of my libraries, my tests started to fail spuriously. 
I started looking at the issue, and after a look of debugging, I was surprised by the behavior of `insertOrFind `.
I expect `insertOrFind` to work as follow:

```
mut = insertOrFind(k)
assert(mut.getValue() == ValueTraits<>::NullValue)
mut = insertOrFind(k)
assert(mut.getValue() == ValueTraits<>::Redirect)
```

But, I encounter sometimes, that on the second `getValue` I get a `NullValue` instead of `Redirect`.

I made the following concrete :

```cpp
#include <mutex>
#include <thread>
#include <vector>
#include <atomic>
#include <cassert>
#include <junction/ConcurrentMap_Leapfrog.h>

using Key = size_t;
using Value = int64_t;

template <typename T>
struct ValueTraits {
    using IntType = T;
    using Value = T;

    static constexpr IntType NullValue = 0;
    static constexpr IntType Redirect = static_cast<T>(-1); // I want -1, not 1 by default for redirect value
};

using hash_map = junction::ConcurrentMap_Leapfrog<Key, Value, junction::DefaultKeyTraits<Key>,
      ValueTraits<Value>>;
using vec_t = std::vector<std::atomic<size_t>>;

void insert(hash_map& m, vec_t& vec, size_t len) {
    for (size_t i = 0; i < len ; ++i) {
        auto mutator = m.insertOrFind(i + 1);
        auto to_insert = mutator.getValue() == ValueTraits<Value>::NullValue;

        if (to_insert)
        {
            mutator.exchangeValue(i + 1);
            ++vec[i];
        }
        assert(vec[i]!=2); // can assert here
    }
}

int main()
{
    constexpr size_t map_size = 2048;
    hash_map m(map_size<<1);
    vec_t vec(map_size);

    for (auto& v : vec)
        v = 0;

    auto t1 = std::thread(insert, std::ref(m), std::ref(vec), map_size);
    auto t2 = std::thread(insert, std::ref(m), std::ref(vec), map_size);

    t1.join();
    t2.join();

    return 0;
}
```

The example does not use directly the value of  `Redirect` but I should normally only insert one time in the map (It reproduce the behavior of my use case).
When you run this example, sometimes in does thrown an assert, sometimes it fails in the `assert`.

Do I make a wrong assumption somewhere or did I implement something wrong?

Thank you for any help you can provide me with.
I tried with `Grampa ` too, same behavior.

Best,
Julián

**Comment by brucejee** [comment]
I read the author's post, and found the cause of assert failed must be insertOrFind is not thread safe, you must add lock  when you want just create only one value for a key.

cite from here: https://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/
Another way is to prevent such collisions entirely using double-checked locking. This approach guarantees that only one object will ever be created for a given key.

```cpp
Foo* value = myMap.get(14);
if (!value) {
    turf::LockGuard<turf::Mutex> lock(someMutex);
    ConcurrentMap::Mutator mutator = myMap.insertOrFind(14);
    value = mutator.getValue();
    if (!value) {
        value = new Foo;
        mutator.assignValue(value);
    }
}
```

**Comment by MonkeyBreaker** [comment]
You are right @brucejee , I did not understood that `insertOrFind` was not thread safe.
Modifying my previous `insert` function as follow does not trigger the assert:

```cpp
turf::Mutex mut;

void insert(hash_map& m, vec_t& vec, size_t len) {
    for (size_t i = 0; i < len ; ++i) {
        auto value = m.get(i + 1);

        if (!value) {
            turf::LockGuard<turf::Mutex> lock(mut);
            auto mutator = m.insertOrFind(i + 1);
            auto to_insert = mutator.getValue() == ValueTraits<Value>::NullValue;
            if (to_insert) {
                mutator.assignValue(i + 1);
                ++vec[i];
            }
        }

        assert(vec[i]!=2);
    }
}
```

I don't know if I am happy with this solution because it requires to add a lock.
I will need to benchmark the impact on the performances on my application.

Anyway, thank you @brucejee, I will close this issue then :)

**Comment by brucejee** [comment]
I just understand `insertOrFind` operation is not linearizable but atomic from the comments of this [post,](https://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/) it means if one thread use `insertOrFind` insert a key into the map, another thread maybe doesn't see this key already exist.
