### ISSUE TITLE
A possible deadlock

### ISSUE THREAD

**Issue by james0zan** [preshing/junction#6]
Hello,

The following code will be stuck at the second get() operation.
Is it a bug or I misuse Junction's API?

```
#include "junction/ConcurrentMap_Grampa.h"
int main() {
  junction::ConcurrentMap_Grampa<uint64_t, uint64_t> m;
  m.set(1, 0);
  m.get(1);
  m.set(1, 1);
  m.get(1);
}
```
According to my investigation, it is stuck at
```
table->jobCoordinator.participate() @ ConcurrentMap_Grampa::get()
    pair.condVar.wait(guard) @ SimpleJobCoordinator::participate()
```

Thx!

**Comment by preshing** [comment]
You can't explicitly set values to the default NullValue (0) or Redirect (1).
It should have triggered an assert (in the Debug or RelWithAsserts config).
You can change those defaults by passing a custom ValueTraits to the template.
I should really document these things better! :)
