### ISSUE TITLE
cmake error: install TARGETS given no ARCHIVE DESTINATION for ... target "turf"

### ISSUE THREAD

**Issue by TooBiased** [preshing/junction#7]
Hi,

line 98 within the turf CMakeLists.txt:
install(TARGETS turf DESTINATION ${LIB_INSTALL_DIR})

LIB_INSTALL_DIR is not set when running cmake from within the junction project.

replacing the variable with "lib" should work.

Best Regards,
Tobias Maier

**Comment by weshoke** [comment]
I have the same issue.

**Comment by chenchienhao** [comment]
Hi, I got same error.
So I need to change `install(TARGETS turf DESTINATION ${LIB_INSTALL_DIR})` => `install(TARGETS turf DESTINATION ${lib})` ?

**Comment by preshing** [comment]
Fixed in preshing/turf@409dcd6
